[mysql]
server = "localhost"
port = 3306
database = "go_rss_aggregator"
user = "go"
password = "go"

[dbmigrations]
files = "db-migrations/"

[server]
port = 3000

[logger]
level = "debug"
encoding = "json"
outputPaths = ["stdout"]
errorOutputPaths = ["stderr"]

[logger.encoderconfig]
messageKey = "message"
levelEncoder = "lowercase"

[syncEngine]
intervalInSeconds = 10
